Add OAK-D demo
husarion/depthai-docker pull request #5
Opened 2024-04-17 12:53 UTC by rafal-gorecki

2024-04-24 18:49 UTC, delihus requested changes

2024-04-24 18:49 UTC, delihus commented on README.md
> +# Docker Images for Luxonis OAX Series cameras
```suggestion
# Docker Images for Luxonis OAK Series cameras
```

2024-04-24 18:49 UTC, delihus commented on README.md
> +The repository includes a GitHub Actions workflow that automatically deploys built Docker images to the [husarion/depthai-docker](https://hub.docker.com/r/husarion/depthai) Docker Hub repositories. T
```suggestion
The repository includes a GitHub Actions workflow that automatically deploys built Docker images to the [husarion/depthai-docker](https://hub.docker.com/r/husarion/depthai) Docker Hub repository. This process is based on [depthai-ros](https://github.com/luxonis/depthai-ros) repository.
```

2024-04-24 18:49 UTC, delihus commented on README.md
> +1. Plugin the Device
```suggestion
1. Plug in the Device
```

2024-04-24 18:49 UTC, delihus commented on README.md
> +1. Clone the Repository
```suggestion
1. Clone the repository
```

2024-04-24 18:49 UTC, delihus commented on README.md
> +2. Activate the Device
```suggestion
2. Activate the device
```

2024-04-24 18:49 UTC, delihus commented on README.md
> +3. Launch Visualization
```suggestion
3. Launch visualization
```

2024-04-24 18:49 UTC, delihus commented on demo/oak-1-theora/Dockerfile
> +        ros-${ROS_DISTRO}-rqt*
I think it is not a good idea to install all `rqt` applications or plugins. Take a look:
https://index.ros.org/search/?term=rqt
![image](https://github.com/husarion/depthai-docker/assets/109142865/93d6df89-d5f5-4703-93db-fa22d66cb23d)

Let's find what plugin is needed maybe only `rqt_image_view`?

2024-04-26 11:07 UTC, rafal-gorecki commented on demo/oak-1-theora/Dockerfile
> +        ros-${ROS_DISTRO}-rqt*
```suggestion
        ros-${ROS_DISTRO}-rqt-image-view
```

2024-04-29 06:52 UTC, delihus approved these changes

2024-05-07 11:28 UTC, merged